# Generated by Django 2.0.5 on 2018-08-19 14:26

import bbricks.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bbricks.models.get_upload_file_name, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='PayingGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Apartment', 'Apartment'), ('Land', 'Land'), ('Independent House', 'Independent House')], max_length=50)),
                ('available_for', models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Both', 'Both')], max_length=50)),
                ('suitable_for', models.CharField(choices=[('Students', 'Students'), ('Professionals', 'Professionals')], max_length=50)),
                ('available_from', models.DateField()),
                ('furnishing', models.CharField(choices=[('Fully furnished', 'Fully furnished'), ('Semi furnished', 'Semi furnished'), ('Unfurnished', 'Unfurnished')], max_length=50)),
                ('rent', models.IntegerField()),
                ('security_deposit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(choices=[('Owner', 'Owner'), ('Dealer', 'Dealer'), ('Builder', 'Builder')], max_length=10)),
                ('project_name', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('area', models.IntegerField()),
                ('units', models.CharField(choices=[('Marla', 'Marla'), ('Acres', 'Acres'), ('Sq.Ft.', 'Sq.Ft.')], max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Apartment', 'Apartment'), ('Land', 'Land'), ('Independent House', 'Independent House')], max_length=50)),
                ('rent_to', models.CharField(choices=[('Family', 'Family'), ('Single Men', 'Single Men'), ('Single Women', 'Single Women')], max_length=50)),
                ('available_from', models.DateField()),
                ('furnishing', models.CharField(choices=[('Fully furnished', 'Fully furnished'), ('Semi furnished', 'Semi furnished'), ('Unfurnished', 'Unfurnished')], max_length=50)),
                ('rent', models.IntegerField()),
                ('security_deposit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Apartment', 'Apartment'), ('Land', 'Land'), ('Independent House', 'Independent House')], max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=bbricks.models.get_upload_file_name)),
                ('mobile_no', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bbricks.Property')),
                ('bedrooms', models.IntegerField()),
                ('balconies', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('age', models.IntegerField()),
                ('parking', models.BooleanField()),
                ('lift', models.BooleanField()),
                ('park', models.BooleanField()),
                ('power_backup', models.CharField(choices=[('None', 'None'), ('Full', 'Full'), ('Partial', 'Partial')], max_length=50)),
                ('property_on_floor', models.IntegerField()),
                ('fire_alarm', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('bbricks.property',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bbricks.Property')),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('floors_allowed', models.IntegerField()),
                ('registered', models.BooleanField()),
                ('price_per_merla', models.IntegerField()),
                ('boundary_wall', models.BooleanField()),
                ('overlooking', models.CharField(blank=True, choices=[('Main Road', 'Main Road'), ('Park', 'Park'), ('Club', 'Club')], max_length=50, null=True)),
            ],
            bases=('bbricks.property',),
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bbricks.Property')),
                ('bedrooms', models.IntegerField()),
                ('balconies', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('age', models.IntegerField()),
                ('parking', models.BooleanField()),
                ('lift', models.BooleanField()),
                ('park', models.BooleanField()),
                ('power_backup', models.CharField(choices=[('None', 'None'), ('Full', 'Full'), ('Partial', 'Partial')], max_length=50)),
                ('water_source', models.CharField(choices=[('Borewell/Tank', 'Borewell/Tank'), ('Municipal Corporation', 'Municipal Corporation')], max_length=50)),
                ('overlooking', models.CharField(blank=True, choices=[('Main Road', 'Main Road'), ('Park', 'Park'), ('Club', 'Club')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('bbricks.property',),
        ),
        migrations.AddField(
            model_name='sell',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.Property'),
        ),
        migrations.AddField(
            model_name='rent',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.City'),
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.UserProfile'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.State'),
        ),
        migrations.AddField(
            model_name='payingguest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.Property'),
        ),
        migrations.AddField(
            model_name='images',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bbricks.Property'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.State'),
        ),
    ]
