# Generated by Django 2.0.5 on 2018-08-15 12:19

import bbricks.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('bedrooms', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to=bbricks.models.get_upload_file_name)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=bbricks.models.get_upload_file_name)),
                ('mobile_no', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.UserProfile'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbricks.State'),
        ),
    ]
